services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html/Minifourchan
      - ./upload:/var/www/html/Minifourchan/upload
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: mini4chan
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db
